### ISSUE TITLE
Macro star expected a Relation but received the value

### ISSUE THREAD

**Issue by Freia3** [dbt-labs/dbt-utils#645]
### Describe the bug
When trying to use the dbt_utils star macro, I get an error message

### Steps to reproduce
test2.sql:
```
select * from omop.person
```
test.sql:
```
select
  {{ dbt_utils.star(ref('test2')) }}
from {{ ref('test2') }}
```
After running dbt run, I get the error message.
### Expected results
dbt run executes successfully

### Actual results
  Macro star expected a Relation but received the value: "dbt_freia"."test"
  
  > in macro _is_relation (macros/cross_db_utils/_is_relation.sql)
  > called by macro default__star (macros/sql/star.sql)
  > called by macro star (macros/sql/star.sql)
  > called by model test (models/test.sql)
12:27:50.552616 [debug] [MainThread]: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dbt/main.py", line 127, in main
    results, succeeded = handle_and_check(args)
  File "/usr/local/lib/python3.8/site-packages/dbt/main.py", line 192, in handle_and_check
    task, res = run_from_args(parsed)
  File "/usr/local/lib/python3.8/site-packages/dbt/main.py", line 246, in run_from_args
    results = task.run()
  File "/usr/local/lib/python3.8/site-packages/dbt/task/runnable.py", line 454, in run
    self._runtime_initialize()
  File "/usr/local/lib/python3.8/site-packages/dbt/task/runnable.py", line 156, in _runtime_initialize
    super()._runtime_initialize()
  File "/usr/local/lib/python3.8/site-packages/dbt/task/runnable.py", line 94, in _runtime_initialize
    self.load_manifest()
  File "/usr/local/lib/python3.8/site-packages/dbt/task/runnable.py", line 81, in load_manifest
    self.manifest = ManifestLoader.get_full_manifest(self.config)
  File "/usr/local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 200, in get_full_manifest
    manifest = loader.load()
  File "/usr/local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 326, in load
    self.parse_project(
  File "/usr/local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 455, in parse_project
    parser.parse_file(block)
  File "/usr/local/lib/python3.8/site-packages/dbt/parser/base.py", line 428, in parse_file
    self.parse_node(file_block)
  File "/usr/local/lib/python3.8/site-packages/dbt/parser/base.py", line 401, in parse_node
    self.render_update(node, config)
  File "/usr/local/lib/python3.8/site-packages/dbt/parser/models.py", line 154, in render_update
    super().render_update(node, config)
  File "/usr/local/lib/python3.8/site-packages/dbt/parser/base.py", line 376, in render_update
    context = self.render_with_context(node, config)
  File "/usr/local/lib/python3.8/site-packages/dbt/parser/base.py", line 267, in render_with_context
    get_rendered(
  File "/usr/local/lib/python3.8/site-packages/dbt/clients/jinja.py", line 597, in get_rendered
    return render_template(template, ctx, node)
  File "/usr/local/lib/python3.8/site-packages/dbt/clients/jinja.py", line 548, in render_template
    return template.render(ctx)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
  File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dbt/clients/jinja.py", line 332, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dbt/clients/jinja.py", line 259, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dbt/clients/jinja.py", line 332, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dbt/clients/jinja.py", line 259, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dbt/clients/jinja.py", line 332, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dbt/clients/jinja.py", line 259, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 3, in template
  File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dbt/exceptions.py", line 1066, in inner
    raise exc
  File "/usr/local/lib/python3.8/site-packages/dbt/exceptions.py", line 1063, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dbt/exceptions.py", line 441, in raise_compiler_error
    raise CompilationException(msg, node)
dbt.exceptions.CompilationException: Compilation Error in model test (models/test.sql)
  Macro star expected a Relation but received the value: "dbt_freia"."test"
  
  > in macro _is_relation (macros/cross_db_utils/_is_relation.sql)
  > called by macro default__star (macros/sql/star.sql)
  > called by macro star (macros/sql/star.sql)
  > called by model test (models/test.sql)

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.4
  - package: dbt-msft/tsql_utils
    version: 0.8.1

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [> ] other (specify: sql server)

**The output of `dbt --version`:**
```
installed version: 1.0.8
```

**Comment by joellabes** [comment]
@Freia3 thanks for submitting this - I can't reproduce it using utils 0.8.6 on Snowflake so I assume that this is a [tsql](https://github.com/dbt-msft/tsql-utils)-specific issue. @dataders I can't transfer this to that repo, are you able to since you're in both orgs?
